### ISSUE TITLE
POST method > Request body can't be obtained

### ISSUE THREAD

**Issue by ffilipus** [Aliics/mouse#4]
Scala: 3.5.2
OS: Win 11
Mouse: 0.5.2

Reprosteps:

Slightly modified example server, trying to echo request body:
```scala
import mouse.*
import mouse.types.*
import org.slf4j.{Logger, LoggerFactory}

import scala.concurrent.ExecutionContext.Implicits.given
import scala.concurrent.Future
import scala.io.Source

private def parse(using request: Request) = Future:
  Response.Ok(
    body =
      // Use Source.fromInputStream to read the InputStream
      val source = Source.fromInputStream(request.body)
      try
        // Read the entire content as a single String
        source.mkString
      finally
        // Always close the source to free resources
        source.close()
  )

@main def hello(): Unit =
  given Logger = LoggerFactory.getLogger("pingServer")
  Server(
    routes (
      Method.Post / "" -> parse
    ) *
  ).runBlocking(port = 8080)
```

Actual:
When sending POST request to `http://localhost:8080` with some payload response from insomnia (REST client) is not obtained.

**Comment by Aliics** [comment]
I had entirely relied on Content-Length here, as it seemed this was the standard behaviour of cURL and browsers generally did their due diligence to provide this header.

I am currently writing 0.6.0 which will patch this, and there will be a helper method `text()` present on the Request and Response types to make it easier to extract this data. :)

**Comment by ffilipus** [comment]
I've tested it with new 0.6.0 method text and it works. Thanks.
